---
title: "DataWrangling"
author: 
date: "2025-11-30"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse);library(lubridate);library(here)
here()
```

```{r Data Import:eGRID}
eGRID23_PLNT <- read.csv(here("Data/egrid2023_data_rev2_PLNT.csv"),
                         na.strings = c("", " ", "0")) %>% 
  slice(-1) %>% 
  mutate(Data.Year=as.Date(paste0(Data.Year, "-01-01"))) %>% 
  mutate(Plant.latitude=as.numeric(Plant.latitude)) %>% 
  mutate(Plant.longitude=as.numeric(Plant.longitude)) %>%
  mutate(Plant.annual.NOx.emissions..tons.=as.numeric(
    Plant.annual.NOx.emissions..tons.)) %>% 
  mutate(Plant.annual.SO2.emissions..tons.=as.numeric(
    Plant.annual.SO2.emissions..tons.)) %>% 
  mutate(Plant.annual.CO2.emissions..tons.=as.numeric(
    Plant.annual.CO2.emissions..tons.)) %>% 
  mutate(Plant.annual.CH4.emissions..lbs.=as.numeric(
    Plant.annual.CH4.emissions..lbs.)) %>% 
  mutate(Plant.annual.N2O.emissions..lbs.=as.numeric(
    Plant.annual.N2O.emissions..lbs.)) %>% 
  mutate(Plant.annual.CO2.equivalent.emissions..tons.=as.numeric(
    Plant.annual.CO2.equivalent.emissions..tons.)) %>% 
  mutate(Plant.annual.Hg.emissions..lbs.=as.numeric(
    Plant.annual.Hg.emissions..lbs.)) %>% 
  select("Data.Year", "Plant.state.abbreviation", "Plant.name", 
         "Plant.county.name", "Plant.latitude", "Plant.longitude", 
         "Plant.primary.fuel","Plant.annual.NOx.emissions..tons.",
         "Plant.annual.SO2.emissions..tons.", "Plant.annual.CO2.emissions..tons.",
         "Plant.annual.CH4.emissions..lbs.","Plant.annual.N2O.emissions..lbs.", 
         "Plant.annual.CO2.equivalent.emissions..tons.", 
         "Plant.annual.Hg.emissions..lbs.")  

eGRID22_PLNT <- read.csv(here("Data/egrid2022_data_PLNT.csv"),
                         na.strings = c("", " ", "0")) %>%
  slice(-1) %>% 
  mutate(Data.Year=as.Date(paste0(Data.Year, "-01-01"))) %>% 
  mutate(Plant.latitude=as.numeric(Plant.latitude)) %>% 
  mutate(Plant.longitude=as.numeric(Plant.longitude)) %>%
  mutate(Plant.annual.NOx.emissions..tons.=as.numeric(
    Plant.annual.NOx.emissions..tons.)) %>% 
  mutate(Plant.annual.SO2.emissions..tons.=as.numeric(
    Plant.annual.SO2.emissions..tons.)) %>% 
  mutate(Plant.annual.CO2.emissions..tons.=as.numeric(
    Plant.annual.CO2.emissions..tons.)) %>% 
  mutate(Plant.annual.CH4.emissions..lbs.=as.numeric(
    Plant.annual.CH4.emissions..lbs.)) %>% 
  mutate(Plant.annual.N2O.emissions..lbs.=as.numeric(
    Plant.annual.N2O.emissions..lbs.)) %>% 
  mutate(Plant.annual.CO2.equivalent.emissions..tons.=as.numeric(
    Plant.annual.CO2.equivalent.emissions..tons.)) %>% 
  mutate(Plant.annual.Hg.emissions..lbs.=as.numeric(
    Plant.annual.Hg.emissions..lbs.)) %>% 
  select("Data.Year", "Plant.state.abbreviation", "Plant.name", 
         "Plant.county.name", "Plant.latitude", "Plant.longitude", 
         "Plant.primary.fuel","Plant.annual.NOx.emissions..tons.",
         "Plant.annual.SO2.emissions..tons.", "Plant.annual.CO2.emissions..tons.",
         "Plant.annual.CH4.emissions..lbs.","Plant.annual.N2O.emissions..lbs.", 
         "Plant.annual.CO2.equivalent.emissions..tons.", 
         "Plant.annual.Hg.emissions..lbs.")

eGRID21_PLNT <- read.csv(here("Data/eGRID2021_data_PLNT.csv"), 
                         na.strings = c("", " ", "0")) %>%
  slice(-1) %>% 
  mutate(Data.Year=as.Date(paste0(Data.Year, "-01-01"))) %>% 
    mutate(Plant.latitude=as.numeric(Plant.latitude)) %>% 
    mutate(Plant.longitude=as.numeric(Plant.longitude)) %>%
    mutate(Plant.annual.NOx.emissions..tons.=as.numeric(
      Plant.annual.NOx.emissions..tons.)) %>% 
    mutate(Plant.annual.SO2.emissions..tons.=as.numeric(
      Plant.annual.SO2.emissions..tons.)) %>% 
    mutate(Plant.annual.CO2.emissions..tons.=as.numeric(
      Plant.annual.CO2.emissions..tons.)) %>% 
    mutate(Plant.annual.CH4.emissions..lbs.=as.numeric(
      Plant.annual.CH4.emissions..lbs.)) %>% 
    mutate(Plant.annual.N2O.emissions..lbs.=as.numeric(
      Plant.annual.N2O.emissions..lbs.)) %>% 
    mutate(Plant.annual.CO2.equivalent.emissions..tons.=as.numeric(
      Plant.annual.CO2.equivalent.emissions..tons.)) %>% 
    mutate(Plant.annual.Hg.emissions..lbs.=as.numeric(
      Plant.annual.Hg.emissions..lbs.)) %>% 
  select("Data.Year", "Plant.state.abbreviation", "Plant.name", 
         "Plant.county.name", "Plant.latitude", "Plant.longitude", 
         "Plant.primary.fuel","Plant.annual.NOx.emissions..tons.",
         "Plant.annual.SO2.emissions..tons.", "Plant.annual.CO2.emissions..tons.",
         "Plant.annual.CH4.emissions..lbs.","Plant.annual.N2O.emissions..lbs.", 
         "Plant.annual.CO2.equivalent.emissions..tons.", 
         "Plant.annual.Hg.emissions..lbs.")


eGRID20_PLNT <- read.csv(here("Data/eGRID2020_Data_v2_PLNT.csv"),
                         na.strings = c("", " ", "0")) %>% 
  slice(-1) %>% 
  mutate(Data.Year=as.Date(paste0(Data.Year, "-01-01"))) %>% 
  mutate(Plant.latitude=as.numeric(Plant.latitude)) %>% 
  mutate(Plant.longitude=as.numeric(Plant.longitude)) %>%
  mutate(Plant.annual.NOx.emissions..tons.=as.numeric(
    Plant.annual.NOx.emissions..tons.)) %>% 
  mutate(Plant.annual.SO2.emissions..tons.=as.numeric(
    Plant.annual.SO2.emissions..tons.)) %>% 
  mutate(Plant.annual.CO2.emissions..tons.=as.numeric(
    Plant.annual.CO2.emissions..tons.)) %>% 
  mutate(Plant.annual.CH4.emissions..lbs.=as.numeric(
    Plant.annual.CH4.emissions..lbs.)) %>% 
  mutate(Plant.annual.N2O.emissions..lbs.=as.numeric(
    Plant.annual.N2O.emissions..lbs.)) %>% 
  mutate(Plant.annual.CO2.equivalent.emissions..tons.=as.numeric(
    Plant.annual.CO2.equivalent.emissions..tons.)) %>% 
  mutate(Plant.annual.Hg.emissions..lbs.=as.numeric(
    Plant.annual.Hg.emissions..lbs.)) %>% 
  select("Data.Year", "Plant.state.abbreviation", "Plant.name", 
         "Plant.county.name", "Plant.latitude", "Plant.longitude", 
         "Plant.primary.fuel","Plant.annual.NOx.emissions..tons.",
         "Plant.annual.SO2.emissions..tons.", "Plant.annual.CO2.emissions..tons.",
         "Plant.annual.CH4.emissions..lbs.","Plant.annual.N2O.emissions..lbs.", 
         "Plant.annual.CO2.equivalent.emissions..tons.", 
         "Plant.annual.Hg.emissions..lbs.")

eGRID19_PLNT <- read.csv(here("Data/egrid2019_data_PLNT.csv"), na.strings = c("", " ", "0")) %>% 
  slice(-1) %>% 
  mutate(Data.Year=as.Date(paste0(Data.Year, "-01-01"))) %>% 
  mutate(Plant.latitude=as.numeric(Plant.latitude)) %>% 
  mutate(Plant.longitude=as.numeric(Plant.longitude)) %>%
  mutate(Plant.annual.NOx.emissions..tons.=as.numeric(
    Plant.annual.NOx.emissions..tons.)) %>% 
  mutate(Plant.annual.SO2.emissions..tons.=as.numeric(
    Plant.annual.SO2.emissions..tons.)) %>% 
  mutate(Plant.annual.CO2.emissions..tons.=as.numeric(
    Plant.annual.CO2.emissions..tons.)) %>% 
  mutate(Plant.annual.CH4.emissions..lbs.=as.numeric(
    Plant.annual.CH4.emissions..lbs.)) %>% 
  mutate(Plant.annual.N2O.emissions..lbs.=as.numeric(
    Plant.annual.N2O.emissions..lbs.)) %>% 
  mutate(Plant.annual.CO2.equivalent.emissions..tons.=as.numeric(
    Plant.annual.CO2.equivalent.emissions..tons.)) %>% 
  mutate(Plant.annual.Hg.emissions..lbs.=as.numeric(
    Plant.annual.Hg.emissions..lbs.)) %>% 
  select("Data.Year", "Plant.state.abbreviation", "Plant.name", 
         "Plant.county.name", "Plant.latitude", "Plant.longitude", 
         "Plant.primary.fuel","Plant.annual.NOx.emissions..tons.",
         "Plant.annual.SO2.emissions..tons.", "Plant.annual.CO2.emissions..tons.",
         "Plant.annual.CH4.emissions..lbs.","Plant.annual.N2O.emissions..lbs.", 
         "Plant.annual.CO2.equivalent.emissions..tons.", 
         "Plant.annual.Hg.emissions..lbs.")

eGRID_PLNT <- rbind (eGRID23_PLNT, eGRID22_PLNT, eGRID21_PLNT, eGRID20_PLNT,
                     eGRID19_PLNT)
eGRID_TX_indiv <- filter(eGRID_PLNT, Plant.state.abbreviation == "TX")
eGRID_PLNT_US <- group_by(eGRID_PLNT, Plant.state.abbreviation,Plant.county.name, Data.Year) %>% 
  summarize(CO2_Equiv = sum(Plant.annual.CO2.equivalent.emissions..tons.)) %>% 
  na.omit()
eGRID_PLNT_TX <- filter(eGRID_PLNT_US,Plant.state.abbreviation == "TX" ) %>% 
  rename(Date = Data.Year) %>% 
  rename(County = Plant.county.name)
```



```{r Data Import: Air Quality}
#TX only PM2.5
TXPM2523 <- read.csv(here("Data/TXPM2523.csv")) %>% 
  mutate(Date=mdy(Date)) %>% 
  select("Date", "Daily.AQI.Value", "Local.Site.Name", "AQS.Parameter.Description", "State", "County", "Site.Latitude", "Site.Longitude") %>% 
  mutate(Year = year(Date)) %>% 
  mutate(Date=as.Date(paste0(Year, "-01-01")))

TXPM2522 <- read.csv(here("Data/TXPM2522.csv")) %>% 
  mutate(Date=mdy(Date)) %>% 
  select("Date", "Daily.AQI.Value", "Local.Site.Name", "AQS.Parameter.Description", "State", "County", "Site.Latitude", "Site.Longitude") %>% 
  mutate(Year = year(Date)) %>% 
  mutate(Date=as.Date(paste0(Year, "-01-01")))

TXPM2521 <- read.csv(here("Data/TXPM2521.csv")) %>% 
  mutate(Date=mdy(Date)) %>% 
  select("Date", "Daily.AQI.Value", "Local.Site.Name", "AQS.Parameter.Description", "State", "County", "Site.Latitude", "Site.Longitude") %>% 
  mutate(Year = year(Date)) %>% 
  mutate(Date=as.Date(paste0(Year, "-01-01")))

TXPM2520 <- read.csv(here("Data/TXPM2520.csv")) %>% 
  mutate(Date=mdy(Date)) %>% 
  select("Date", "Daily.AQI.Value", "Local.Site.Name", "AQS.Parameter.Description", "State", "County", "Site.Latitude", "Site.Longitude") %>% 
  mutate(Year = year(Date)) %>% 
  mutate(Date=as.Date(paste0(Year, "-01-01")))

TXPM2519 <- read.csv(here("Data/TXPM2519.csv")) %>% 
  mutate(Date=mdy(Date)) %>% 
  select("Date", "Daily.AQI.Value", "Local.Site.Name", "AQS.Parameter.Description", "State", "County", "Site.Latitude", "Site.Longitude") %>% 
  mutate(Year = year(Date)) %>% 
  mutate(Date=as.Date(paste0(Year, "-01-01")))

#All Texas PM2.5 2018 - 2023 by County
TXPM25 <- rbind(TXPM2519, TXPM2520, TXPM2521, TXPM2522, TXPM2523)
TXPM25_CNTY <- TXPM25 %>% 
  group_by(Date, County) %>% 
  summarize(Avg_AQI_PM25 = mean(Daily.AQI.Value))

#TX only Ozone
TXOzone23 <- read.csv(here("Data/TXOzone23.csv")) %>% 
  mutate(Date=mdy(Date)) %>% 
  select("Date", "Daily.AQI.Value", "Local.Site.Name", "AQS.Parameter.Description", "State", "County", "Site.Latitude", "Site.Longitude") %>% 
  mutate(Year = year(Date)) %>% 
  mutate(Date=as.Date(paste0(Year, "-01-01")))

TXOzone22 <- read.csv(here("Data/TXOzone22.csv")) %>% 
  mutate(Date=mdy(Date)) %>% 
  select("Date", "Daily.AQI.Value", "Local.Site.Name", "AQS.Parameter.Description", "State", "County", "Site.Latitude", "Site.Longitude") %>% 
  mutate(Year = year(Date)) %>% 
  mutate(Date=as.Date(paste0(Year, "-01-01")))

TXOzone21 <- read.csv(here("Data/TXOzone21.csv")) %>% 
  mutate(Date=mdy(Date)) %>% 
  select("Date", "Daily.AQI.Value", "Local.Site.Name", "AQS.Parameter.Description", "State", "County", "Site.Latitude", "Site.Longitude") %>% 
  mutate(Year = year(Date)) %>% 
  mutate(Date=as.Date(paste0(Year, "-01-01")))

TXOzone20 <- read.csv(here("Data/TXOzone20.csv")) %>% 
  mutate(Date=mdy(Date)) %>% 
  select("Date", "Daily.AQI.Value", "Local.Site.Name", "AQS.Parameter.Description", "State", "County", "Site.Latitude", "Site.Longitude") %>% 
  mutate(Year = year(Date)) %>% 
  mutate(Date=as.Date(paste0(Year, "-01-01")))

TXOzone19 <- read.csv(here("Data/TXOzone19.csv")) %>% 
  mutate(Date=mdy(Date)) %>% 
  select("Date", "Daily.AQI.Value", "Local.Site.Name", "AQS.Parameter.Description", "State", "County", "Site.Latitude", "Site.Longitude") %>% 
  mutate(Year = year(Date)) %>% 
  mutate(Date=as.Date(paste0(Year, "-01-01")))

#All Texas Ozone 2018 - 2023 by County
TXOzone <- rbind(TXOzone19, TXOzone20, TXOzone21, TXOzone22, TXOzone23)
TXOzone_CNTY <- TXOzone %>% 
  group_by(Date, County) %>% 
  summarize(Avg_AQI_Ozone = mean(Daily.AQI.Value))
```

```{r Wrangling: Emissions and AQI}
#TX Emissions and AQI
TXEmissions_PM25 <- left_join(TXPM25_CNTY, eGRID_PLNT_TX, 
                              by = c("Date", "County")) %>% 
  na.omit()
TXEmissions_Ozone <- left_join(TXOzone_CNTY, eGRID_PLNT_TX, 
                              by = c("Date", "County")) %>% 
  na.omit()
```

```{r Wrangling: Harris County AQI and Rain data}

TXOzoneHarris <- TXOzone %>%
  filter(County == 'Harris')%>%
  group_by(Date) %>%
  summarise(Avg_AQI_Ozone = mean(Daily.AQI.Value))

HarrisCoRain <- read.csv(here("Data/HarrisCoRain.csv"))%>%
  na.omit(PRCP)%>%
  group_by(DATE) %>%
  summarise(Avg_Rain = mean(PRCP))%>%
  mutate(Date=mdy(DATE))%>%
  select("Date","Avg_Rain")



```

