---
title: "Xia Meng version of Maeve's Data wrangling"
author: "Xia Meng Howey"
date: "2025-12-08"
output: html_document
---


```{r setup, include=FALSE}
library(tidyverse);library(lubridate);library(here)
here()
```

```{r Data Import:eGRID}
eGRID23_PLNT <- read.csv(here("Data/egrid2023_data_rev2_PLNT.csv"),
                         na.strings = c("", " ", "0")) %>% 
  slice(-1) %>% 
  mutate(Data.Year=as.Date(paste0(Data.Year, "-01-01"))) %>% 
  mutate(Plant.latitude=as.numeric(Plant.latitude)) %>% 
  mutate(Plant.longitude=as.numeric(Plant.longitude)) %>%
  mutate(Plant.annual.NOx.emissions..tons.=as.numeric(
    Plant.annual.NOx.emissions..tons.)) %>% 
  mutate(Plant.annual.SO2.emissions..tons.=as.numeric(
    Plant.annual.SO2.emissions..tons.)) %>% 
  mutate(Plant.annual.CO2.emissions..tons.=as.numeric(
    Plant.annual.CO2.emissions..tons.)) %>% 
  mutate(Plant.annual.CH4.emissions..lbs.=as.numeric(
    Plant.annual.CH4.emissions..lbs.)) %>% 
  mutate(Plant.annual.N2O.emissions..lbs.=as.numeric(
    Plant.annual.N2O.emissions..lbs.)) %>% 
  mutate(Plant.annual.CO2.equivalent.emissions..tons.=as.numeric(
    Plant.annual.CO2.equivalent.emissions..tons.)) %>% 
  mutate(Plant.annual.Hg.emissions..lbs.=as.numeric(
    Plant.annual.Hg.emissions..lbs.)) %>% 
  select("Data.Year", "Plant.state.abbreviation", "Plant.name", 
         "Plant.county.name", "Plant.latitude", "Plant.longitude", 
         "Plant.primary.fuel","Plant.annual.NOx.emissions..tons.",
         "Plant.annual.SO2.emissions..tons.", "Plant.annual.CO2.emissions..tons.",
         "Plant.annual.CH4.emissions..lbs.","Plant.annual.N2O.emissions..lbs.", 
         "Plant.annual.CO2.equivalent.emissions..tons.", 
         "Plant.annual.Hg.emissions..lbs.")  

eGRID22_PLNT <- read.csv(here("Data/egrid2022_data_PLNT.csv"),
                         na.strings = c("", " ", "0")) %>%
  slice(-1) %>% 
  mutate(Data.Year=as.Date(paste0(Data.Year, "-01-01"))) %>% 
  mutate(Plant.latitude=as.numeric(Plant.latitude)) %>% 
  mutate(Plant.longitude=as.numeric(Plant.longitude)) %>%
  mutate(Plant.annual.NOx.emissions..tons.=as.numeric(
    Plant.annual.NOx.emissions..tons.)) %>% 
  mutate(Plant.annual.SO2.emissions..tons.=as.numeric(
    Plant.annual.SO2.emissions..tons.)) %>% 
  mutate(Plant.annual.CO2.emissions..tons.=as.numeric(
    Plant.annual.CO2.emissions..tons.)) %>% 
  mutate(Plant.annual.CH4.emissions..lbs.=as.numeric(
    Plant.annual.CH4.emissions..lbs.)) %>% 
  mutate(Plant.annual.N2O.emissions..lbs.=as.numeric(
    Plant.annual.N2O.emissions..lbs.)) %>% 
  mutate(Plant.annual.CO2.equivalent.emissions..tons.=as.numeric(
    Plant.annual.CO2.equivalent.emissions..tons.)) %>% 
  mutate(Plant.annual.Hg.emissions..lbs.=as.numeric(
    Plant.annual.Hg.emissions..lbs.)) %>% 
  select("Data.Year", "Plant.state.abbreviation", "Plant.name", 
         "Plant.county.name", "Plant.latitude", "Plant.longitude", 
         "Plant.primary.fuel","Plant.annual.NOx.emissions..tons.",
         "Plant.annual.SO2.emissions..tons.", "Plant.annual.CO2.emissions..tons.",
         "Plant.annual.CH4.emissions..lbs.","Plant.annual.N2O.emissions..lbs.", 
         "Plant.annual.CO2.equivalent.emissions..tons.", 
         "Plant.annual.Hg.emissions..lbs.")

eGRID21_PLNT <- read.csv(here("Data/eGRID2021_data_PLNT.csv"), 
                         na.strings = c("", " ", "0")) %>%
  slice(-1) %>% 
  mutate(Data.Year=as.Date(paste0(Data.Year, "-01-01"))) %>% 
    mutate(Plant.latitude=as.numeric(Plant.latitude)) %>% 
    mutate(Plant.longitude=as.numeric(Plant.longitude)) %>%
    mutate(Plant.annual.NOx.emissions..tons.=as.numeric(
      Plant.annual.NOx.emissions..tons.)) %>% 
    mutate(Plant.annual.SO2.emissions..tons.=as.numeric(
      Plant.annual.SO2.emissions..tons.)) %>% 
    mutate(Plant.annual.CO2.emissions..tons.=as.numeric(
      Plant.annual.CO2.emissions..tons.)) %>% 
    mutate(Plant.annual.CH4.emissions..lbs.=as.numeric(
      Plant.annual.CH4.emissions..lbs.)) %>% 
    mutate(Plant.annual.N2O.emissions..lbs.=as.numeric(
      Plant.annual.N2O.emissions..lbs.)) %>% 
    mutate(Plant.annual.CO2.equivalent.emissions..tons.=as.numeric(
      Plant.annual.CO2.equivalent.emissions..tons.)) %>% 
    mutate(Plant.annual.Hg.emissions..lbs.=as.numeric(
      Plant.annual.Hg.emissions..lbs.)) %>% 
  select("Data.Year", "Plant.state.abbreviation", "Plant.name", 
         "Plant.county.name", "Plant.latitude", "Plant.longitude", 
         "Plant.primary.fuel","Plant.annual.NOx.emissions..tons.",
         "Plant.annual.SO2.emissions..tons.", "Plant.annual.CO2.emissions..tons.",
         "Plant.annual.CH4.emissions..lbs.","Plant.annual.N2O.emissions..lbs.", 
         "Plant.annual.CO2.equivalent.emissions..tons.", 
         "Plant.annual.Hg.emissions..lbs.")


eGRID20_PLNT <- read.csv(here("Data/eGRID2020_Data_v2_PLNT.csv"),
                         na.strings = c("", " ", "0")) %>% 
  slice(-1) %>% 
  mutate(Data.Year=as.Date(paste0(Data.Year, "-01-01"))) %>% 
  mutate(Plant.latitude=as.numeric(Plant.latitude)) %>% 
  mutate(Plant.longitude=as.numeric(Plant.longitude)) %>%
  mutate(Plant.annual.NOx.emissions..tons.=as.numeric(
    Plant.annual.NOx.emissions..tons.)) %>% 
  mutate(Plant.annual.SO2.emissions..tons.=as.numeric(
    Plant.annual.SO2.emissions..tons.)) %>% 
  mutate(Plant.annual.CO2.emissions..tons.=as.numeric(
    Plant.annual.CO2.emissions..tons.)) %>% 
  mutate(Plant.annual.CH4.emissions..lbs.=as.numeric(
    Plant.annual.CH4.emissions..lbs.)) %>% 
  mutate(Plant.annual.N2O.emissions..lbs.=as.numeric(
    Plant.annual.N2O.emissions..lbs.)) %>% 
  mutate(Plant.annual.CO2.equivalent.emissions..tons.=as.numeric(
    Plant.annual.CO2.equivalent.emissions..tons.)) %>% 
  mutate(Plant.annual.Hg.emissions..lbs.=as.numeric(
    Plant.annual.Hg.emissions..lbs.)) %>% 
  select("Data.Year", "Plant.state.abbreviation", "Plant.name", 
         "Plant.county.name", "Plant.latitude", "Plant.longitude", 
         "Plant.primary.fuel","Plant.annual.NOx.emissions..tons.",
         "Plant.annual.SO2.emissions..tons.", "Plant.annual.CO2.emissions..tons.",
         "Plant.annual.CH4.emissions..lbs.","Plant.annual.N2O.emissions..lbs.", 
         "Plant.annual.CO2.equivalent.emissions..tons.", 
         "Plant.annual.Hg.emissions..lbs.")

eGRID19_PLNT <- read.csv(here("Data/egrid2019_data_PLNT.csv"), na.strings = c("", " ", "0")) %>% 
  slice(-1) %>% 
  mutate(Data.Year=as.Date(paste0(Data.Year, "-01-01"))) %>% 
  mutate(Plant.latitude=as.numeric(Plant.latitude)) %>% 
  mutate(Plant.longitude=as.numeric(Plant.longitude)) %>%
  mutate(Plant.annual.NOx.emissions..tons.=as.numeric(
    Plant.annual.NOx.emissions..tons.)) %>% 
  mutate(Plant.annual.SO2.emissions..tons.=as.numeric(
    Plant.annual.SO2.emissions..tons.)) %>% 
  mutate(Plant.annual.CO2.emissions..tons.=as.numeric(
    Plant.annual.CO2.emissions..tons.)) %>% 
  mutate(Plant.annual.CH4.emissions..lbs.=as.numeric(
    Plant.annual.CH4.emissions..lbs.)) %>% 
  mutate(Plant.annual.N2O.emissions..lbs.=as.numeric(
    Plant.annual.N2O.emissions..lbs.)) %>% 
  mutate(Plant.annual.CO2.equivalent.emissions..tons.=as.numeric(
    Plant.annual.CO2.equivalent.emissions..tons.)) %>% 
  mutate(Plant.annual.Hg.emissions..lbs.=as.numeric(
    Plant.annual.Hg.emissions..lbs.)) %>% 
  select("Data.Year", "Plant.state.abbreviation", "Plant.name", 
         "Plant.county.name", "Plant.latitude", "Plant.longitude", 
         "Plant.primary.fuel","Plant.annual.NOx.emissions..tons.",
         "Plant.annual.SO2.emissions..tons.", "Plant.annual.CO2.emissions..tons.",
         "Plant.annual.CH4.emissions..lbs.","Plant.annual.N2O.emissions..lbs.", 
         "Plant.annual.CO2.equivalent.emissions..tons.", 
         "Plant.annual.Hg.emissions..lbs.")

#combine 2019-2023 egrid data into one dataframe
eGRID_PLNT <- rbind (eGRID23_PLNT, eGRID22_PLNT, eGRID21_PLNT, eGRID20_PLNT,
                     eGRID19_PLNT)

#filter above df for just Texas
eGRID_TX_indiv <- filter(eGRID_PLNT, Plant.state.abbreviation == "TX")

#Sum CO2 equiv at county level
#XH added: Sum CH4 at county level
eGRID_PLNT_US <- group_by(eGRID_PLNT, Plant.state.abbreviation,
                          Plant.county.name, Data.Year) %>% 
  summarize(
    CO2_Equiv = sum(Plant.annual.CO2.equivalent.emissions..tons., na.rm = TRUE),
    Annual_CH4_lb = sum(Plant.annual.CH4.emissions..lbs., na.rm = TRUE)
    ) %>% 
  filter(CO2_Equiv != 0, Annual_CH4_lb != 0) %>% 
  ungroup()
  
#filter for just Texas (county level)
eGRID_PLNT_TX <- filter(eGRID_PLNT_US,Plant.state.abbreviation == "TX" ) %>% 
  rename(Date = Data.Year) %>% 
  rename(County = Plant.county.name) 
```
